### ISSUE TITLE
thrown errors on hidden files e.g. .DS_Store

### ISSUE THREAD

**Issue by mikolayek** [tnicola/cypress-parallel#10]
Currently script scans directory and treats all files in selected directory as spec files.
I got error on `.DS_Store`, so it might occur with other files e.g. `.gitignore`.

It would be nice to have one of the options available:

- hardcoded filtering files and include *.js only
- possibility to define filter in -d option, or additional option, which will do filtering out for user

e.g. 
```bash
# --include option
cypress-parallel -s cy:run -t 3 -d ./cypress/integration/examples --include *.js
# -- exclude option
cypress-parallel -s cy:run -t 3 -d ./cypress/integration/examples --exclude *.docx
```

Thrown error you can find below.
```
 npm
  ERR! code ELIFECYCLE
npm ERR! errno 1

 npm
 ERR! lenta-testing@1.0.0 cy:run: `cypress run "--reporter" "cypress-parallel/json-stream.reporter.js" "--spec" "'cypress/integration/examples/.DS_Store'"`
npm ERR! Exit status 1

 npm ERR!

npm ERR! Failed at the lenta-testing@1.0.0 cy:run script.

 npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by saki2rules** [comment]
I'm also facing the exact same issue. 
Also version - 0.1.8 is not available on the npm. Can you please look into it.

**Comment by catchwhale** [comment]
Seems to be an issue but interesting concerned, hope we any update on it

**Comment by mikolayek** [comment]
Repository have bunch pull requests waiting for merge since July. I think it would be better to fork project and fix that issue by ourselves :(

**Comment by sbagade-chwy** [comment]
I am facing the same problem. Any resolution to the issue?
