### ISSUE TITLE
Cypress Parallel With Arguments not working

### ISSUE THREAD

**Issue by rahil1998** [tnicola/cypress-parallel#116]
Hello Folks,

Cypress Parallel was working fine, but the one issue I was facing with passing custom cypress arguments as it does not take place.
I tried to pass the base URL via env if anyone has an idea what was wrong or what's missing.

![image](https://user-images.githubusercontent.com/94888349/178240409-e0ae75d6-e2d9-42d0-bcff-cc504ce54937.png)

Thanks

**Comment by tnicola** [comment]
@rahil1998 Replying a bit late on this: when using npx you don't need to escape the double quotes with the backslash:

`npx cypress-parallel -s cypress:run -t 5 -d 'cypress/e2e/**/*.cy.js -a '"--config baseUrl=https://dev.mytesting.com"'`

As pointed out by @joshuajtward , you need to use `--config` to set the `baseUrl`
