### ISSUE TITLE
Threads run all specs when less specs then treads are found

### ISSUE THREAD

**Issue by Jsijbel** [tnicola/cypress-parallel#129]
When there are for example 2 specs found, but the command was ran with 3 or more threads configured the first 2 agents run the correct specs but the 3rd and more agents run all specs. This complicates the configuration a lot when automating the running of specs with the parallel plugin.

![image](https://user-images.githubusercontent.com/39823861/191740463-c9e35908-5bec-47b8-b324-fed0f92cafb8.png)

It would be nice if the package took the found tests into account when starting threads, and not start more threads then specs.

So when 3 threads are configured, but only 2 specs were found only 2 threads would be started.

**Comment by Jsijbel** [comment]
Also created a pull request.

https://github.com/tnicola/cypress-parallel/pull/130

**Comment by VinceOPS** [comment]
I can confirm the same unexpected behavior here with v0.10.0 (mac os 12+, apple M1 pro, yarn v1, node 16)

**Comment by tnicola** [comment]
This should be fixed now. Thanks @Jsijbel !
