### ISSUE TITLE
[Feature request] Support folder structure

### ISSUE THREAD

**Issue by nessor** [tnicola/cypress-parallel#20]
It would be great if the plugin would also support a folder structure. So e.g. ```-d cypress/interactive/**/ ``` where ** stands for any number of folders.
It seems that currently only one folder with all files on one level is supported?

**Comment by jtolotta** [comment]
@nessor The sub-directory can be set using a forward-slash and it will execute all tests in that directory and all sub-directories in that location.

```
cypress-parallel -s cy:run -t 2 -d cypress/integration/mobile-app/
```

I agree that a "glob" will make this better.

**Comment by tnicola** [comment]
Should be working now. Please check out the new version 0.6.0.
