### ISSUE TITLE
Summation problem on Pending tests

### ISSUE THREAD

**Issue by janetlee** [tnicola/cypress-parallel#24]
I think there might be a summation problem. Note the results in the last box for pending tests vs the box right above it.

I know that this reports 14 failing tests, but in the detail of my table, there's only 2 tests that fail. This does not correlate to MaxListener problems while taking test recordings. I see those and have counted them with the failed tests and it doesn't add up to 14.

<img width="698" alt="Screen Shot 2021-03-03 at 1 33 16 PM" src="https://user-images.githubusercontent.com/5065781/109862588-9da35900-7c2e-11eb-90c4-36c683099cb7.png">

I do like this package though. It's pretty nifty and reduces my run time by about 45-55% (~1600-1800 in the UI, vs 730-980 in parallel mode). Thanks!

**Comment by tnicola** [comment]
This should be solved in v. 0.2.0
