### ISSUE TITLE
Tests Skipped in a feature is not displayed in reporting

### ISSUE THREAD

**Issue by prasanmgc** [tnicola/cypress-parallel#27]
Let's say, I have 2 features with 2 tests each. 
Feature 1 - 2 smoke tests
Feature 2 - 1 smoke & 1 regression tests

If i use this plugin to execute smoke tests, only feature 1 is displayed in the console report. Feature 2 is not displayed.
I tried printing the [test] and found that only for the feature where all the tests executed, suiteEnd is displayed and not for the feature thats partially executed.

Root cause Assumption - 
`if (test[0] === 'suiteEnd' && test[1].title != null) {
                        timeMap.set(test[1].title, { ...test[1], duration: suiteDuration });
                    }`

Could someone please look into it?

**Comment by tnicola** [comment]
Hi @prasanmgc , 
Do you have this problem only when you skip some of the tests?
Are you able to reproduce this in the plugin demo-app?

**Comment by prasanmgc** [comment]
Hi @tnicola , it is not possible to reproduce this in the current demo-app. it doesn't use cypress-cucumber format. above example should be helpful to reproduce. In my case, 
Feature 1 - 7 smoke tests
Feature 2 - 31 mixed tests (different tags - 1 smoke, 27 regression, 3 negative)

so when i run smoke tests, Feature 2 execution is fine but not reported anywhere in this plugin. but it is reported in my own reports.

**Comment by prasanmgc** [comment]
Just to add to the issue, the root cause is mocha suite end event doesn't get triggered for the features that has partial execution. so relying on this event doesn't help to capture the partial execution details. I have customised the logic by using the 'EVENT_SUITE_BEGIN' and 'EVENT_RUN_END'. i.e. capture the suite title & start time from 'EVENT_SUITE_BEGIN' event and compare that against 'EVENT_RUN_END' event.

**Approach:**
1. pushing title and start time to an array.
2. then compare that against the start from the finish time and get the title.
3. fetchTitle is customised function to compare the value in an array.

**Code**
`if (test[0] === 'suiteStart') {
                        if (test[1].title) {
                            tests.push({ title: test[1].title, startTime: test[1].start });
                        }
                    }
                    if (test[0] === 'finish') {
                        let feature = fetchTitle(tests, 'startTime', test[1].start);
                        if (feature) {
                            timeMap.set(feature.title, { ...test[1], duration: suiteDuration });
                        }
                    }`

**Report:**
![image](https://user-images.githubusercontent.com/55723986/111721259-9bd6c800-88b3-11eb-80ff-55d1d0cfba37.png)
