### ISSUE TITLE
Use the `integrationFolder` from cypress.json

### ISSUE THREAD

**Issue by tomardern** [tnicola/cypress-parallel#29]
Hi,

Great repo, looking forward to having a play.

Instead of passing through `--specsDir` (and then default to `integration`), what about using the `integrationFolder` parameter from cypress.json?

Just an idea :)

**Comment by prasanmgc** [comment]
AFAIK, this plugin relies on the arguments supplied at run time through the scripts. and not everyone will be defining the integrationFolder in cypress.json. Most of them go by default folder structure, unless you have a different requirement/needs.
Also, only cypress runner can read/update values in cypress.json.

To implement the above, there needs to be unnecessary complexity being introduced in the plugin. i.e. to read the cypress.json file for the 'integrationFolder' value. but again, no guarantee that this value won't be changed at run time like other variables like 'baseURL'. 

As said earlier, this implementation would be less consumed and specific to customised folder structure , as most will go for default folder structure(recommended by cypress). so its better to give the user ability to pass the customised folder structure or use the default.

**Comment by tomardern** [comment]
@prasanmgc sure, makes sense. Thanks for explaining.
