### ISSUE TITLE
My System keeps restarting as soon as I run test in parallel

### ISSUE THREAD

**Issue by kunalashar25** [tnicola/cypress-parallel#32]
OS: Mac
Version: 11.0.1

Git Repo
https://github.com/kunalashar25/learn-cypress

Executing using command
`npm run cy:parallel`

Please let me know why am I facing this issue.

**Comment by prasanmgc** [comment]
Mate,
your project seems to be fine except for the below issues. These issues are not related to cypress-parallel plugin.
**Issues:**
1. package.json - you have declared the below, but it won't work until you implement feature files and step definitions in your project.
`"cypress-cucumber-preprocessor": {
    "nonGlobalStepDefinitions": false,
    "commonPath": "cypress/integration/sample_project/step_definition",
    "stepDefinitions": "cypress/integration/sample_project/step_definition"
  },`
2.plugins -> index.js - you have declared to use the cypress-cucumber-preprocessor but you haven't implemented the cucumber in your project. So the cypress-cucumber-preprocessor plugin looks for the step definitions in the path specified in the package.json. Just comment those code as below and run your script. it will work.
`//on('file:preprocessor', cucumber())`

Please read through the cypress-cucumber-preprocessor documentation for cypress-cucumber implementation.
[https://github.com/TheBrainFamily/cypress-cucumber-preprocessor](url)

Hope this helps. Please close this issue, once you accept this solution.

**Comment by kunalashar25** [comment]
thank you. It worked after removing it.
