### ISSUE TITLE
/usr/bin/env: ‘node\r’: No such file or directory error

### ISSUE THREAD

**Issue by devsalsa** [tnicola/cypress-parallel#36]
Quick question, does the package run only on Windows so far?

When I try to execute it on a Linux machine (Ubuntu), I got the following error:

```
/usr/bin/env: ‘node\r’: No such file or directory
error Command failed with exit code 127.
```

To fix it temporarily, I just have to edit the cli.js file to replace CRLF with LF in the first line and then it works great.

But it means currently I can't easily integrate it in our project for all my developers + I'd like to test it in our CI :-)

**Comment by tnicola** [comment]
@devsalsa I still haven't tried it on Linux yet. I'll try to address this issue, in the meanwhile, if you have a quick solution, feel free to open a PR

**Comment by devsalsa** [comment]
@tnicola new release when you have time please :pray:

**Comment by tnicola** [comment]
@devsalsa 0.2.1 published

**Comment by devsalsa** [comment]
mmm it didn't fix the problem. Maybe because only the `lib` folder is published.

**Comment by tnicola** [comment]
Ok, my bad. I think the problem was publishing directly from my local with the wrong eol. Check out the 0.2.2 version

**Comment by devsalsa** [comment]
Yep you fixed the problem :-) thank you
