### ISSUE TITLE
Facing performance issue in parallel execution

### ISSUE THREAD

**Issue by T-e-j-k-u-m-a-r** [tnicola/cypress-parallel#53]
Hi, 

I have a smoke suite with 21 scripts which takes 5 mins to execute in single thread chrome headed mode, Where when the same is tried with 4 thread parallel execution mode, The execution takes 12 minutes and below are parallel observations. 

1. CPU utilization during execution is above 80%
2. Memory Utilization during execution is above 75%
3. The application hangs 

Cypress Version: 8.3.1

**Comment by modern-sapien** [comment]
I'm interested to see what time savings you get with 2 machines.  

What you're encountering is exactly what Cypress explains will happen when utilizing parallelization on a single machine, resources can get maxed out and you end up costing yourself more time in the long run.

**Comment by tnicola** [comment]
Well, what @modern-sapien says is correct, it totally depends on your machine. 

e.g.: I'm using it on a Mac, 2,3 GHz 8-Core Intel Core i9, with 16 GB 2667 MHz DDR4 and with parallelization set to 8 threads I'm getting 75% of savings in terms of time, you have to find the right compromise based on your machine power, probably you won't get any benefit using more than 2 parallel threads.
