### ISSUE TITLE
Video Recording not working in latest release

### ISSUE THREAD

**Issue by amcinerneynewf** [tnicola/cypress-parallel#55]
I just updated to today's new release (https://github.com/tnicola/cypress-parallel/releases/tag/0.5.0) and cypress video recording is no longer working 

Error from console: 
```
13:44:46  Warning: We failed to record the video.
13:44:46  
13:44:46  This error will not alter the exit code.
13:44:46  
13:44:46  Error: ffmpeg exited with code 1: /home/ubuntu/workspace/[branch]/cypress/videos/[filepath].mp4: No such file or directory
13:44:46  
13:44:46      at ChildProcess.<anonymous> (/home/ubuntu/.cache/Cypress/8.3.1/Cypress/resources/app/packages/server/node_modules/fluent-ffmpeg/lib/processor.js:182:22)
13:44:46      at ChildProcess.emit (events.js:315:20)
13:44:46      at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
```

I'm not sure if this error is actually being caused by the new changes to this package or is an issue in cypress that was suddenly uncovered by the recent changes. I found a related issue here where other people seem to have a similar issue: https://github.com/cypress-io/cypress/issues/9128#issuecomment-896401759

reproduction steps: 
in **cypress.json** set `"video": true,` and then run cypress-parallel via command line

info: 
Cypress: v8.3.0
cypress-parallel: v0.5.0
run environment: ci/cypress run/jenkins and my local machine's macOS
browser: electron 91

possibly relevant: 
  `"viewportWidth": 1920,`
  `"viewportHeight": 1080`
  https://github.com/cypress-io/cypress/issues/3491#issuecomment-464222564

**Comment by Nyeng** [comment]
Same here. Seems to be an issue for anything but 2 threads?

**Comment by VlasovSergey** [comment]
It looks like a cypress issue because we've tried to run cypress in several processes without `cypress-parallel` and have had the same issue.

**Comment by tnicola** [comment]
@amcinerneynewf @Nyeng Are you still experimenting this or was it related to Cypress?

**Comment by yravid** [comment]
Hi @amcinerneynewf, did you find a solution for this error? thanks

**Comment by Nyeng** [comment]
I left the project where I added Cypress tests, so I haven't gotten the chance to revisit this issue... I ended up disabling video recordings. Would test it if there's a known fix that addresses this issue though? @tnicola

**Comment by guywmustang** [comment]
I solved this by adding a sleep before the tests run to allow the cleanup of video files before threads start doing anything:

In `cypress.config.js`:
```
// Helper function to create a delay
const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));
```

```
setupNodeEvents(on, config) {
      // Wait 10 seconds before starting the tests to ensure the environment is ready (takes time
      // to delete the video files before the threads start running)
      on('before:run', async (details) => {
        console.log("---- START PRE-TEST WAIT ----");
        await sleep(10000);
        console.log("---- END PRE-TEST WAIT ----");
      });
      // Limit ffmpeg to 1 thread per video-recording process - don't know if this is necessary
      on('before:spec', (spec) => {
        process.env.FFMPEG_ARGS = '-threads 1';
      });
...
```

--- 

This allows not setting `trashAssetsBeforeRuns` in `cypress.config.js`, or setting it to `true`.
