### ISSUE TITLE
ENAMETOOLONG in runner-result

### ISSUE THREAD

**Issue by BarkhatovN** [tnicola/cypress-parallel#64]
Hello!
I have an issue with ENAMETOOLONG
the problem is we have deep hierarchical directory structure. it causes very long name in runner-result, so we face ENAMETOOLONG error.
Looks like we need api to control runner-result names to solve the problem

**Comment by BarkhatovN** [comment]
Oh, obviously i can create report for myself to fix it. Thank you for this!

**Comment by tnicola** [comment]
Hi @BarkhatovN , how long is it your hierarchical structure? - Did you solve it with a custom reporter?

**Comment by BarkhatovN** [comment]
Hi @tnicola , i don't really remember the correct number, but we are using cyrillic names of 2-3 levels of folder. 
Yes, i did. Just change file result names like that `const specResultPath = path.join(resultsPath, uuidv4() + '.json');`
