### ISSUE TITLE
Error message in latest release : 'Node.js, fs.rmdir(path, { recursive: true }) will be removed'

### ISSUE THREAD

**Issue by ISanjeevKumar** [tnicola/cypress-parallel#66]
Getting below error message after installing latest release 0.5.0.

(node:5337) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
node:fs:1526
  handleErrorFromBinding(ctx);

is anyone facing the same issue?

**Comment by stevenmchaves** [comment]
I believe some of the open PRs would resolve this issue.

**Comment by ISanjeevKumar** [comment]
Checked with latest version , all looks fine now.
