### ISSUE TITLE
ERROR: env: node\r: No such file or directory

### ISSUE THREAD

**Issue by hyposlasher** [tnicola/cypress-parallel#67]
When I try to run cy:parallel`cy:parallel` it exits with error:
```
env: node\r: No such file or directory
error Command failed with exit code 127.
```

command looks like this:
`"cy:parallel" : "cypress-parallel -s cypress:run -t 2 -d cypress",`

**Comment by stevenmchaves** [comment]
Do you have cypress:run defined in package.json? Does cypress directory contain any tests?

**Comment by hyposlasher** [comment]
@stevenmchaves 
```
    "cypress:run": "cypress run --browser chrome --headless -c video=false",
```
![image](https://user-images.githubusercontent.com/13961762/140752966-e3dd7dc4-b2df-4377-ad89-5f2e3936ed46.png)

**Comment by stevenmchaves** [comment]
try cypress/integration for the directory or just integration

**Comment by hyposlasher** [comment]
@stevenmchaves the same error for both

**Comment by mfittko** [comment]
it's written on windows, which produce bad line wraps. I could fix this and add a pr @tnicola fine for you?

**Comment by ISanjeevKumar** [comment]
@hyposlasher  did you change anything in cli.js file ?

**Comment by hyposlasher** [comment]
@ISanjeevKumar no

**Comment by Zeioth** [comment]
Same issue here. I've been able to use it in the past, the only new thing in my setup is nvm

```
/usr/bin/env: «node\r»: No existe el fichero o el directorio
/usr/bin/env: use -[v]S to pass options in shebang lines
error Command failed with exit code 127.
```

**Comment by ISanjeevKumar** [comment]
I faced the same issue and after replacing cleanResultsPath function with my own custom method in cli.js file , it works fine for me.

You can also try and check if it works for you or not just by commenting cleanResultsPath at line 23 in cli.js file.
@Zeioth @hyposlasher

**Comment by hyposlasher** [comment]
@ISanjeevKumar still doesn't work
![image](https://user-images.githubusercontent.com/13961762/144117509-144988e9-460b-4ce4-a8ef-2ea5e9475932.png)

**Comment by mfittko** [comment]
Just fix the line breaks with dos2unix. Preferably here in this repo ;)

**Comment by ISanjeevKumar** [comment]
@hyposlasher Just go to node_modules/cypress-parallel path via terminal and type below command.

vim cli.js

:se ff=unix
:wq

it will work for sure.

![image](https://user-images.githubusercontent.com/82697454/144169350-5111eaeb-0b40-462d-bac2-c2a13ba34e2f.png)

**Comment by jozibrewer** [comment]
+1 for this issue.  I can't run in a docker container because of line endings.

**Comment by hyposlasher** [comment]
@ISanjeevKumar approve :)

**Comment by jozibrewer** [comment]
@tnicola Any chance we could get a minor release with this fix in it? 🙏 I love the results I'm getting with this package locally, and would love to try it in a pipeline. 😃

**Comment by tnicola** [comment]
@jozibrewer Should be working now in version 0.6.0!Let me know if you find any issue. Thanks @ISanjeevKumar
