### ISSUE TITLE
Running cypress-parallel directly from command line (not via scripts)

### ISSUE THREAD

**Issue by bennymeade** [tnicola/cypress-parallel#79]
Is it possible to run cypress-parallel directly from command line i.e `npx cypress-parallel cypress run -t 2 -d cypress/integration/*`?

Reason I ask is that I'm trying to get this working inside a large mono repo and I cannot use scripts.

**Comment by tnicola** [comment]
There was a missing dependency. Now it should be working fine using `npx`. 
e.g.: `npx cypress-parallel -s cy:run -t 4 -d 'cypress/integration/1/*.js'`

**Comment by tnicola** [comment]
Ah, I see now your point! What about moving out from the script the `cd tests` part? 
Then using it from the command line: `cd tests && npx cypress-parallel -s 'cy:run' -t 1 -d 'tests/cypress/integration/*/*.ts'`, where cy:run is defined as: `"cy:run": "cypress run --browser chrome"`. May that work on your repo?

**Comment by bennymeade** [comment]
Script = **"cy:run": "cypress run --browser chrome",**

Run command = **cd tests && npx cypress-parallel -s 'cy:run' -t 1 -d 'cypress/integration/*/*.ts' --verbose**

Logs:
```
cd tests && npx cypress-parallel -s 'cy:run' -t 1 -d 'cypress/integration/*/*.ts' --verbose
Using pattern cypress/integration/*/*.ts to find test suites
107 test suite(s) found.
Paths to found suites
[
  "cypress/integration/xyz/abc.spec.ts",
...
]
```
Then after listing all the specs in an array (verbose I guess), it shows this warning:
`Weight file not found in path: cypress/parallel-weights.json`

Then it lists all the specs as a cypress run command:
```
> cypress run --browser chrome "--spec" "'cypress/integration/xyz/abc.spec.ts,.......
```
Then it displays the error that kills the run. And this is correct because my cypress.json is 1 level deeper in **/Code/company/packages/web/corporate/tests**

```Could not find a Cypress configuration file, exiting.
We looked but did not find a default config file in this folder: /Code/company/packages/web/corporate```

This is one of the pains of large mono-repos!

**Comment by tnicola** [comment]
Ok, at least we're making some progress :) 

About the warning: you can ignore this (I will downlevel to info). The error instead it's due to `cypress` itself complaining about not finding any config file in the project root path. Can you try to pass it as a config in your script?

Something like: `"cy:run": "cypress run --browser chrome --config-file path/to-your-config-file.json"`

**Comment by bennymeade** [comment]
That's a good idea. But then my packages paths are out of sync!
```
Could not load reporter by name: cypress-multi-reporters

We searched for the reporter in these paths:

- /packages/web/corporate/tests/cypress-multi-reporters
- /packages/web/corporate/tests/node_modules/cypress-multi-reporter
```
Changing my reporter path in cypress.json doesn't seem to help:
`"reporter": "../node_modules/cypress-multi-reporters",`

In fairness this is not an issue with your package, I have your package working nicely in a small personal repo. This is mono-repo madness, and I would still need the main Cypress commands to work too. So I'm gonna have to give up. Thanks for your help @tnicola

**Comment by tnicola** [comment]
Sorry to hear that!There are some good advantages in monorepos too, but yeah I agree that still you have to handle a lot of unexpected issue. BTW, the cypress-multi-reporters not found could be an issue related to cypress-parallel. I'm trying to fix it here: https://github.com/tnicola/cypress-parallel/issues/72 . I'll keep you up to date just in case you'll try this again in the future!
