### ISSUE TITLE
support for run-ct command

### ISSUE THREAD

**Issue by hcho112** [tnicola/cypress-parallel#85]
Hello,

Our team is trying to adopt component testing of cypress and wonders if we can run them in parallel locally. 
I have tried using `cypress-parallel` package to run in parallel, hoping that I just need to swap `run` command to `run-ct`.  But unfortunately it did not work.

Before I start pasting error messages and my attempts, I would like to know if it is officially supported (or it is possible) from this repo, or has anyone successfully got it working. 

Cheers

**Comment by ISanjeevKumar** [comment]
@hcho112 this is will work in local machine without any issue. can help If you can share the error message.

**Comment by tnicola** [comment]
Hey @hcho112 , were you able to get this working?

**Comment by hcho112** [comment]
My apologies for late update. Our team decided not to proceed with cypress unit testing so I kind of stopped investigating the issue.

**Comment by Phonesis** [comment]
I am using Cypress for React based component testing and cannot get it to work in parallel. I think what happens is that Webpack is launched for each thread and, as a result, only 1 webpack instance is able to launch in parallel? So as a result only 1 thread ever actually runs. I am using this script (specs exist in src folder): 

```
    "cy:parallel": "cypress-parallel -s cy:ct:run -t 2 -d src/**/*.spec.cy.tsx",
```
The run starts but Webpack shuts down for one of the threads:

**Comment by Phonesis** [comment]
Quick update on above for anyone who has similar problem. I was able to fix shortly after typing the above! I needed to remove a hard coded port value from the webpack config. So it was down to a port conflict. With that removed webpack assigns each instance a free port within the 8000 range. Seems ok now.
