### ISSUE TITLE
npm Cypress command arguments via -a results as baseUrl is null

### ISSUE THREAD

**Issue by bennymeade** [tnicola/cypress-parallel#93]
I need to use `-a` option within the command line, as it will become an input parameter in my GitHub workflow. But when I pass `-a` option in the command line this results as baseUrl is null.

Is this an issue in the latest version or I'm doing something wrong?

```
"devDependencies": {
    "cypress": "^9.5.1",
    "cypress-multi-reporters": "^1.5.0",
    "cypress-parallel": "^0.9.0"
  }
```

```
"scripts": {
    "cy:run": "cypress run --browser chrome"
  },
```
Run command:
```
npx cypress-parallel -s cy:run -t 2 -d cypress/integration -a '\"--config baseUrl=https://example.cypress.io\"'
```
**baseUrl is null**

![image](https://user-images.githubusercontent.com/1033474/158194281-c9ac15a1-3870-447c-97cf-d6ba6c16a291.png)

**Works fine with regular Cypress run command**
```
$ npx cypress open --config baseUrl=https://example.cypress.io
```

![image](https://user-images.githubusercontent.com/1033474/158195552-77d58277-b330-4ab3-b0cf-c3a111b6ad5e.png)

**Also passing the option in script does work:**
```
"scripts": {
    "cy:run": "cypress run --browser chrome --config baseUrl=https://example.cypress.io"
  },

$ npx cypress-parallel -s cy:run -t 2 -d cypress/integration
```
![image](https://user-images.githubusercontent.com/1033474/158196963-eebc5b31-a515-4067-93fc-b7f1d49c9440.png)

**Comment by jdini76** [comment]
is this issue still open? I am using 0.9.1 and I am not able to pass arguments to the cypress script.

**Comment by rushelex** [comment]
Просто удалите обратный слэш из агрументов:
```sh
npx cypress-parallel -s cy:run -t 2 -d cypress/integration -a '"--config baseUrl=https://example.cypress.io"'
```

**Comment by tnicola** [comment]
Sorry, a bit too late on this: I confirm if you're using npx you don't need the backslash to escape double quotes.
